### ISSUE TITLE
Users should be able to review which cells were identified for N-size supression

### ISSUE THREAD

**Issue by sethltaylor** [P20WCommunityOfInnovation/DisclosureAvoidance#3]
- After a user specifies an N-size parameter, they should be able to review which cells are identified for suppression based on this parameter prior to suppression being applied. 
- The tool should produce a log, file, or other method of reporting the cells identified for suppression

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
Completed by #1

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
Completed by #1
