### ISSUE TITLE
Add Redact Zero Functionality

### ISSUE THREAD

**Issue by VT-AOE-DMAD-Drew-Bennett** [P20WCommunityOfInnovation/DisclosureAvoidance#62]
Washington asked if zero could be redacted in the primary redaction process instead of ignored. To resolve this issue we are going to add another arguement to represent this need.

**Comment by amstutzg1** [comment]
@VT-AOE-DMAD-Drew-Bennett do you think it makes sense to make this its own function, or do you think it would make sense to just rope it into another function (maybe `less_than_threshold_not_zero` or `redact_user_requested_records`)?

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
@amstutzg1 I think wrapping it into less_than_threshold_not_zero  makes sesnse and renaming it less than threshold.

**Comment by sethltaylor** [comment]
Closed by #67
