### ISSUE TITLE
Users should be able to see what data was redacted and for what reason

### ISSUE THREAD

**Issue by sethltaylor** [P20WCommunityOfInnovation/DisclosureAvoidance#9]
- The tool should produce a final dataframe and/or output file with data appropriately redacted based on specified parameters.
- The tool should also produce a log identifying which cells were redacted along with a reason for redaction (e.g. "Cell was below specified N-size", "Cell was redacted due to complementary suppression.")

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
Complete with pull request #1

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
Complete with pull request #1
